[workspace]
authors = ["Paul Dutton <jodgey4@gmail.com>"]
channels = ["conda-forge"]
name = "ziglox"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
tests = "zig build test --summary all"
doit = "clear && zig build run -- test.lox"

[dependencies]
zig = ">=0.15.1,<0.16"

[tool.pixi.scripts]
alias = "echo 'alias zbr=\"zig build run -- \"' >> $BASH_ENV"
